export const authConstants ={
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const userConstants ={
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
}

export const categoryConstants ={
    GET_ALL_CATEGORY_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_FAILURE: 'GET_ALL_CATEGORY_FAILURE',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_FAILURE: 'ADD_NEW_CATEGORY_FAILURE',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    UPDATE_CATEGORRIES_REQUEST: 'UPDATE_CATEGORRIES_REQUEST',
    UPDATE_CATEGORRIES_FAILURE: 'UPDATE_CATEGORRIES_FAILURE',
    UPDATE_CATEGORRIES_SUCCESS: 'UPDATE_CATEGORRIES_SUCCESS',
    DELETE_CATEGORRIES_REQUEST: 'DELETE_CATEGORRIES_REQUEST',
    DELETE_CATEGORRIES_FAILURE: 'DELETE_CATEGORRIES_FAILURE',
    DELETE_CATEGORRIES_SUCCESS: 'DELETE_CATEGORRIES_SUCCESS',
}

export const productConstants ={
    GET_ALL_PRODUCT_REQUEST: 'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_FAILURE: 'GET_ALL_PRODUCT_FAILURE',
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
}

export const initialDataConstants ={
    GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_FAILURE: 'GET_ALL_INITIAL_DATA_FAILURE',
    GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
}

export const pageConstants ={
    CREATE_PAGE_REQUEST: 'CREATE_PAGE_REQUEST',
    CREATE_PAGE_FAILURE: 'CREATE_PAGE_FAILURE',
    CREATE_PAGE_SUCCESS: 'CREATE_PAGE_SUCCESS',
}