
export const categoryConstants ={
    GET_ALL_CATEGORY_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_FAILURE: 'GET_ALL_CATEGORY_FAILURE',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
}

export const productsConstants = {
    GET_ALL_PRODUCT_SLUG: 'GET_ALL_PRODUCT_SLUG'
}
